### PR TITLE
Adds virtual OnAwakeNetwork callback to NetworkBehaviour

### PR DESCRIPTION
**Pull request by ooonush**
I'm currently developing a Stats System asset for a FishNet and want my NetworkBehaviour to initialize before the others. For that I need an analogue of Unity Awake() method. I would be glad if you could accept this PR.

```csharp
public override void OnAwakeNetwork() // Called before OnStartNetwork
{
    base.OnAwakeNetwork();
}

public override void OnStartNetwork()
{
    base.OnStartNetwork();
}
```

### CODE REVIEW

**Comment by FirstGearGames** [comment]
Not sure I want to merge this, seems excessive.
I can expose this though to be set at runtime; it's inside NetworkObject

```cs
        /// <summary>
        /// Order to initialize this object's callbacks when spawned with other NetworkObjects in the same tick. Default value is 0, negative values will execute callbacks first.
        /// </summary>
        public sbyte GetInitializeOrder() => _initializeOrder;
        [Tooltip("Order to initialize this object's callbacks when spawned with other NetworkObjects in the same tick. Default value is 0, negative values will execute callbacks first.")]
        [SerializeField]
        private sbyte _initializeOrder = 0;
```

**Comment by ooonush** [comment]
I have a NetworkBehaviour and there may be other NetworkBehaviours on the same object. I need my script to initialize over the network before everyone else.

**Comment by FirstGearGames** [comment]
The initialize order will ensure the networkobject performs callbacks
before others, but it does not affect the NetworkBehaviors on the same
object. The NBs are however iterated in the order they're added to the
object; not sure if this applies after sorting them.
Adding another callback won't really solve the problem though because
someone could just use the new callback and you'd end up in the same place.

**Comment by FirstGearGames** [comment]
Closed due to inactivity.

**Pull request closed without merging**
