### PR TITLE
Add IsSpawnable toggle on NetworkObject, for inclusion in DefaultPrefabObjects

### PR DESCRIPTION
**Pull request by FREEZX**
Add IsSpawnable to NetworkObject, as discussed here:
https://github.com/FirstGearGames/FishNet/discussions/518

### CODE REVIEW

**Comment by FirstGearGames** [comment]
A couple requested changes before merging...

bool IsSpawnable does not need a setter at this time so please make it `public bool IsSpawnable => _isSpawnable;` for now.

`if (nob != null && (nob.IsSpawnable || !settings.SpawnableOnly))` is used several times in one class. Make a nested method 
```cs
CanAddNetworkObject(NetworkObject networkObject)
{
    return (nob != null && (nob.IsSpawnable || !settings.SpawnableOnly));
}```

And there's a `void Spawn` in the ServerManager and ClientManager that need to check if IsSpawnable is false, and if so error out.

**Comment by FREEZX** [comment]
@FirstGearGames I did the changes, just not sure about the ClientManager spawn check you mentioned. Looks like both server spawning and predicted spawning use the common Spawn function in `ServerManager.QOL.cs`

**Comment by FirstGearGames** [comment]
It's possible the client spawn redirects there. I'll check it out, ty.

**Comment by FirstGearGames** [comment]
The null check is redundant in these line since it's done in the 'CanAdd...` method.
`if (nob != null && CanAddNetworkObject(nob, settings))`

**Comment by FREEZX** [comment]
Fixed

**Comment by FirstGearGames** [comment]
IsSpawnable was default to false where it should have been true since SpawnableOnly is true. Almost broke everyones' project :P Made changes internally though, will be in 4.0.7!

**Comment by FREEZX** [comment]
> IsSpawnable was default to false where it should have been true since SpawnableOnly is true. Almost broke everyones' project :P Made changes internally though, will be in 4.0.7!

I honestly think that is the better behaviour.
Fixing "Broken" projects will just require you to toggle SpawnableOnly, whereas if IsSpawnable defaults to false, you don't get the memory benefits out of the box.

**Pull request merged**
