### PR TITLE
VarInt Implementation (Loop Unrolled)

### PR DESCRIPTION
**Pull request by TsFreddie**
**This one is the same as #19, but the loop is unrolled**

Replace the PackRate indicator with 7-bit packing.

A full ulong integer will be packed as so:
```
EDDDDDDD EDDDDDDD EDDDDDDD EDDDDDDD XXXXDDDD DDDDDDDD DDDDDDDD DDDDDDDD DDDDDDDD

E = Extension bit (0 means the current byte is the last byte)
D = Data bits
X = eXtra bits (a 4 bit integer indicating how many extra bytes of 8 bit data are following)
```

Signed integer will be ZigZag encoded where the sign bit is moved to the least significant bit and the value is inverted.
E.g. -1 will be encoded as `0b1` instead of full 64 bits of 1s, and 1 will be encoded as `0b10`.

Value bounds (unsigned):

| Bytes | PackRate | 7-bit VarInt   | Mirror VarInt   |
|-------|----------|-----------|----------|
| 1     | N/A      | 127       | 240      |
| 2     | 255      | 16383 | 2287     |
| 3     | 32767    | 2097151 | 67823    |
| 4     | N/A      | 268435455 | 16777215 |
| 5     | 2^32-1   | 2^32-1    | 2^32-1   |
| 6     | N/A      | 2^40-1    | 2^40-1   |
| 7     | N/A      | 2^48-1    | 2^48-1   |
| 8     | N/A      | 2^56-1    | 2^56-1   |
| 9     | 2^64-1   | 2^64-1    | 2^64-1   |

### CODE REVIEW

**Comment by FirstGearGames** [comment]
I've not forgotten about this. I'm looking at it after I get the 1.3x stable out.

**Comment by FirstGearGames** [comment]
This failed test on writing ints.
`using FishNet.Serializing;
using System.Collections.Generic;
using UnityEngine;

public class NumericPackTest : MonoBehaviour
{

    public int Iterations = 1;
    public int Writes = 500;

    public string Output = "unset";

    private void Awake()
    {


        System.Random r = new System.Random();

        for (int z = 0; z < Iterations; z++)
        {

            PooledWriter writer = WriterPool.GetWriter();
            List<int> randomInts = new List<int>(Writes);
            for (int i = 0; i < Writes; i++)
                randomInts.Add(RandomInt());

            List<long> randomLongs = new List<long>(Writes);
            for (long i = 0; i < Writes; i++)
                randomLongs.Add(RandomLong());


            List<uint> randomUInts = new List<uint>(Writes);
            for (int i = 0; i < Writes; i++)
                randomUInts.Add(RandomUInt());

            List<ulong> randomULongs = new List<ulong>(Writes);
            for (long i = 0; i < Writes; i++)
                randomULongs.Add(RandomULong());

            //Write all randoms.
            Output = "Failed writing Ints";
            foreach (var item in randomInts)
                writer.WriteInt32(item);
            Output = "Failed writing Longs";
            foreach (var item in randomLongs)
                writer.WriteInt64(item);
            Output = "Failed writing UInts";
            foreach (var item in randomUInts)
                writer.WriteUInt32(item);
            Output = "Failed writing ULongs";
            foreach (var item in randomULongs)
                writer.WriteUInt64(item);

            //Test written.
            PooledReader reader = ReaderPool.GetReader(writer.GetArraySegment(), null);
            //int32
            Output = "Failed reading Ints";
            for (int i = 0; i < Writes; i++)
            {
                int value = reader.ReadInt32();
                int target = randomInts[i];
                if (value != target)
                {
                    Debug.LogError($"Int32 mismatch. Read {value}, expected {target}");
                    return;
                }
            }
            //int64
            Output = "Failed reading Longs";
            for (int i = 0; i < Writes; i++)
            {
                long value = reader.ReadInt64();
                long target = randomLongs[i];
                if (value != target)
                {
                    Debug.LogError($"Int64 mismatch. Read {value}, expected {target}");
                    return;
                }
            }
            //uint32
            Output = "Failed reading UInts";
            for (int i = 0; i < Writes; i++)
            {
                uint value = reader.ReadUInt32();
                uint target = randomUInts[i];
                if (value != target)
                {
                    Debug.LogError($"UInt32 mismatch. Read {value}, expected {target}");
                    return;
                }
            }
            //unt64
            Output = "Failed reading ULongs";
            for (int i = 0; i < Writes; i++)
            {
                ulong value = reader.ReadUInt64();
                ulong target = randomULongs[i];
                if (value != target)
                {
                    Debug.LogError($"UInt64 mismatch. Read {value}, expected {target}");
                    return;
                }
            }

            reader.Dispose();
            writer.Dispose();
        }

        Output = "Iterations completed successfully!";

        int RandomInt()
        {
            int val = r.Next(int.MinValue, int.MaxValue);
            if (val < int.MinValue || val > int.MaxValue)
            {
                Debug.LogError($"Invalid int generated {val}");
                return 0;
            }

            return val;
        }
        uint RandomUInt()
        {
            uint val = (uint)(RandomInt() * 2);
            if (val < 0 || val > uint.MaxValue)
            {
                Debug.LogError($"Invalid uint generated {val}");
                return 0;
            }

            return val;
        }

        long RandomLong()
        {
            long val = (r.Next(int.MinValue, int.MaxValue) * 2);
            if (val < long.MinValue || val > long.MaxValue)
            {
                Debug.LogError($"Invalid long generated {val}");
                return 0;
            }

            return val;
        }
        ulong RandomULong()
        {
            ulong val = (ulong)(RandomLong() * 2);
            if (val < 0 || val > ulong.MaxValue)
            {
                Debug.LogError($"Invalid ulong generated {val}");
                return 0;
            }

            return val;
        }


    }

}
`

**Comment by TsFreddie** [comment]
Updated and rebased. Forgot to grow the buffer. Added an extra method for that, because having the logic in the unrolled clauses  looks messy. I can update if you prefer to manually inline it.

**Comment by FirstGearGames** [comment]
This has been implemented in my developer branch and will be available in 1.3.4.Nightly.4

**Pull request closed without merging**
