### PR TITLE
Unify NetworkManager default component creation

### PR DESCRIPTION
**Pull request by Nigel-C**
Replace all default component creation methods with a single method.

Verified that all default components are created in play mode.

### CODE REVIEW

**Comment by FirstGearGames** [comment]
Looks good, great refactor! Will also get this in next release.

**Comment by FirstGearGames** [comment]
Added, will be in 2.6.1.
I made one minor change...

```
            _objectPool = GetOrCreateComponent<ObjectPool>(_objectPool);

        private T GetOrCreateComponent<T>(T presetValue = null) where T : UnityEngine.Component
        {
            //If already set then return set value.
            if (presetValue != null)
                return presetValue;

            if (gameObject.TryGetComponent<T>(out T result))
                return result;
            else
                return gameObject.AddComponent<T>();
        }
        ```

**Comment by Nigel-C** [comment]
Alternatively you could also keep the assignment to one line by doing 

```cs
_objectPool = _objectPool ?? GetOrCreateComponent<DefaultObjectPool>();
```

**Comment by FirstGearGames** [comment]
Definitely, but then I'd have to refactor a lot more code to match that style which I'm not ready to do haha.

**Comment by Nigel-C** [comment]
Refactoring always has to start somewhere ;)

Thanks for taking a look at this. I've been reading the code to understand how it all works in more detail. It's been helpful both for learning about networking, and for finding things I didn't know about Unity.

**Pull request closed without merging**
