### PR TITLE
Avoid resetting sync vars to initial values unexpectedly

### PR DESCRIPTION
**Pull request by petergiuntoli**
An object marked as deinitializing can still be referenced as it's not destroyed yet. Attempting to write dirty sync types on the object can cause bugs in external code where the sync vars are now in an unexpected state. This avoids that reset.

My assumption is that this code is here to hide a bug for pooled objects but it executes even on objects that will be completely destroyed. If that's true, perhaps there's a better fix for writing to sync var types or maybe this code is obsolete? I notice that there's an early out inside SetValue which maybe is trying to solve the same problem?

https://github.com/FirstGearGames/FishNet/blob/main/Assets/FishNet/Runtime/Object/Synchronizing/SyncVar.cs#L162-L164

### CODE REVIEW

**Comment by FirstGearGames** [comment]
Why would you try to send a sync value change is the object is being deinitialized? When an object is deinitializing the states should be reset.

**Comment by petergiuntoli** [comment]
> Why would you try to send a sync value change is the object is being deinitialized? 

We're not trying to send a sync value, fish seems to do that itself. The bug we see is that we have a system that runs and despawns things with 0 health but the game object still exists because fishnet delays the destruction. Other systems might still have pending events referencing that game object and if fish tries to serialize it the values will be reset so those systems will end up looking at an object with unexpected state.

For example our game server checks for the health of all players and sees  if they all reach 0. We end up having bugs where there is a "blip" where health goes to 0, then for a tick it's at "initial value", then the next tick the object is destroyed.

> When an object is deinitializing the states should be reset.

Since these game objects aren't being recycled at all there should not be any state resetting because it's just wasted work since the object won't be reused. If the object is recycled, I still think that there likely shouldn't be any state resetting until the object is taken out of the pool again to avoid similar issues.

**Comment by FirstGearGames** [comment]
This must be as clienthost? The delayed destruction happens because server
has to send data to client side, and it's destroyed after client processes
it.

I cannot take this as a PR without knowing the exact cause though. It
shouldn't be possible to dirty a SyncType if deinitializing, and SyncTypes
are sent during despawn message right before deinitializing, which would
clear the dirty status.

So this could be a bug but I need to know the source before I could accept
a PR.

**Comment by petergiuntoli** [comment]
Inside `ManagedObjects.cs` at the very end of  `internal virtual void Despawn(NetworkObject nob, DespawnType despawnType, bool asServer)` I added the following code (exposing some private things for ease of use)

https://github.com/FirstGearGames/FishNet/blob/main/Assets/FishNet/Runtime/Managing/Object/ManagedObjects.cs#L226-L228
```
if (!nob.IsSpawned)
{
    foreach (var thing in nob.NetworkBehaviours)
    {
        if (NetworkManager.ServerManager.Objects._dirtySyncTypeBehaviours.Contains(thing))
        {
            throw new System.Exception();
        }
    }
}
```
The exception fires so I'm assuming the bug is that the object isn't cleared from the `_dirtySyncTypeBehaviours` which causes it to try to be replicated later on. Maybe that's supposed to be happening in `FinalizeDespawn()`? 

https://github.com/FirstGearGames/FishNet/blob/main/Assets/FishNet/Runtime/Managing/Server/Object/ServerObjects.cs#L838-L846
```
private void FinalizeDespawn(NetworkObject nob, DespawnType despawnType)
{
    if (nob != null && nob.ObjectId != NetworkObject.UNSET_OBJECTID_VALUE)
    {
        nob.WriteDirtySyncTypes();
        WriteDespawnAndSend(nob, despawnType);
        CacheObjectId(nob);

        // TODO: Remove from _dirtySyncTypeBehaviours?
    }
}
```

**Comment by FirstGearGames** [comment]
I responded via email but it apparently did not make it to this PR. 

SyncTypes are written at an interval and when despawned. I noticed the interval one was clearing dirty status but the despawned one was not. So the proper fix is clear dirty status after writing SyncTypes for despawn, which I see you figured out in your code example below.

If you want to make a PR the dirty has to be cleared on the SyncType and in the '_dirtySyncTypeBehaviours'. I can do it myself as well, I have another v3 release coming out soon.

**Comment by petergiuntoli** [comment]
@FirstGearGames I added a commit with a proposed fix for not clearing out the dirty behaviors from the list. It became a bit more involved since I think we always want to flush on the reliable channel and we always want to ensure we reset the sync var state on respawn.

I still think it's a good change to avoid resetting to initial values inside this codepath so I kept that commit in.

**Comment by FirstGearGames** [comment]
I don't have enough time to review this by the 407 release so you may need to reapply your changes there. But I'll get this in by 408 which should be shortly after.

**Comment by FirstGearGames** [comment]
408 was an urgent hot fix but this is the only thing left stopping us from a stable v4 release so this 100% will be in 409 any day now!

**Comment by FirstGearGames** [comment]
Decided to wrap this up tonight. I made some very slight alterations.

In SyncBase `ResetState` now resets dirty state and channel rather than going through ResetDirty.

In method WriteDirtySyncTypes rather than rename ignoreInterval to isDespawn I added another boolean `forceReliable`. SyncBase now has internal SetCurrentChannel, and channel check includes use of forceReliable.
```cs
                    if (forceReliable)
                        sb.SetCurrentChannel(Channel.Reliable);
                    //Find channel.
                    byte channel = (byte)sb.Channel;
```

**Pull request merged**
