### PR TITLE
Substream

### PR DESCRIPTION
**Pull request by viliwonka**
PR that adds SubStreams feature into FN to be used in RPC & Broadcasts.

What is new:
* Substream struct
* Substream serialize/deserialize function
* SubReaderPool

What is modified:
* WriterPool now has two internal stacks of writers, small and big
* WriterPool.GetWriter & WriterPool.Recycle

Would be happy to get it tested before merge (I believe you have internal tests). I want that feedback, especially about hot path, to see how I can further improve & minimize overhead on current performance.

### CODE REVIEW

**Comment by FirstGearGames** [comment]
I've been wanting to get this in but it does modify quite a few files. I know we talked about your reasonings for wanting this previously, but could you remind me again on this issue.

Was it you wanted support for a specific type, have the ability to target larger buffers to prevent resizing, ect?

**Comment by viliwonka** [comment]
Initial idea of SubStream is that developers can directly de/serialize data, and that stream can be used inside RPCs or Broadcasts, it enables ease of development (and should be more optimized) instead of playing around with pre-existing byte[] arrays and sending that in RPCs/Broadcasts.

Over time of development I figured that, although the code worked, there were always big GC allocations.
Issue is that buffer pools (writer pools I think) can get depleted, when there is creation of new NetworkObjects. 
In short, there is existing code, that takes buffers from pool for long time (semi-permament). 

Since there is no differentiation of buffer sizes, a very large writer can be taken from pool by something, that requires very small buffer, for a long time, and next time SubStream is used for larger data transfer, new writer is created & the buffers get resized again (just to be taken by something else for long time that requires small buffers).

The issue with this problem (soft mem leak?) exists without SubStreams, I believe it can be seen with creating lots of NetworkObjects and using RPCs with large byte[] arrays simultaneously, so I think it is separate issue from SubStreams itself, but realistically that should not be an issue with simple multiplayer games.

Honestly, I don't know how to alleviate that issue correctly yet, but I will take second look when need for this arises.

**Comment by viliwonka** [comment]
SubStreams already work as intended.

Reading is zero GC, it references existing reader inside custom serialization function for SubStream class, so no copying occurs.

Writing is copy based, since users write in-advance before actual RPC/Broadcast begins.
So, I don't know what you mean by "custom writers".

**Comment by viliwonka** [comment]
By the way, "lots of files touched" is because of that "soft-mem-leak" fix for different sized buffers. SubStream code itself touches only like 4 files I believe.

**Comment by FirstGearGames** [comment]
Let's ignore the idea of substreams at the moment. You could do fine with simply having the large buffer allocations gone, right?

**Comment by viliwonka** [comment]
Not sure really, probably would be doable with lots of Lists I believe, but yes large buff allocs gone would be good.

**Comment by FirstGearGames** [comment]
I've looked over this a few times and the internal files changed are evolving so frequently I don't believe I'll be able to submit this as-is. 

I will 100% be allowing developers to drop the writer of their choosing into RPCs though. With this, you can keep your own pool of large writers and use them to prevent allocs. Broadcasts are planned too but I haven't looked into the ease of that much, though I expect it to be easier since broadcasts don't actually use codegen.

**Comment by viliwonka** [comment]
I can pick this up and fix the conflicts (to end of the week) if you wish :))

**Comment by FirstGearGames** [comment]
I'm going to close this out because an alternative option has been planned. It's on the roadmap, no ETA for complation yet.

**Comment by FirstGearGames** [comment]
please see https://github.com/FirstGearGames/FishNet/issues/105

**Pull request closed without merging**
