### PR TITLE
make listening on IPv6 address configurable

### PR DESCRIPTION
**Pull request by stgrosshh**
On Linux machines in enterprise environments, IPv6 may be disabled and listening on IPv6 addresses lead to an exception in LiteNetLib low level stuff. In consequence IPv4 is not correctly initialized as well. Server side then is not able to send back to client.

With this PR, IPv6 can be disabled by a flag in the Tugboat component.

### CODE REVIEW

**Comment by FirstGearGames** [comment]
I see you even made it true as the default to prevent a break. Thanks :)

**Comment by FirstGearGames** [comment]
Thanks for this but I'm going to decline the v3 branch because it's in LTS. FishNet v4 stable is coming out any day now as well, so there is that. I merged your v4 one, appreciate it!

**Comment by stgrosshh** [comment]
> Thanks for this but I'm going to decline the v3 branch because it's in LTS. FishNet v4 stable is coming out any day now as well, so there is that. I merged your v4 one, appreciate it!

I think you merged the v3 one by accident?

**Comment by FirstGearGames** [comment]
Perhaps so but it does not really matter. A new v4 and v3 are coming out with the changes in. Long as you're credited for the PR we're good.

**Pull request closed without merging**
