### PR TITLE
Edit misleading warning message on nested NetworkObjects

### PR DESCRIPTION
**Pull request by emredesu**
Currently, when the user tries to change a NetworkObject's parent into another NetworkObject, this fails and the user is warned with the error message, saying ` (object) cannot have the parent changed because it is a nested Prefab`. However, the issue is not caused by being a nested prefab, but being a nested NetworkObject. This will lead to the users (like myself :D) being mislead by this error message, and trying to fix it by unpacking their prefabs, which will not work either.

### CODE REVIEW

**Comment by FirstGearGames** [comment]
You can move a NOB into being a child then out again. The restriction is specific to nested prefabs that you cannot.

**Comment by emredesu** [comment]
> You can move a NOB into being a child then out again. The restriction is specific to nested prefabs that you cannot.

Oh is that so? I thought de-parented NOBs were not allowed to be re-parented at all (it's what the documentation states too). What makes some specific prefabs not allowed to be nested by re-parenting again while the others are allowed?

**Comment by FirstGearGames** [comment]
Can you show me what you are referring to please.
You cannot unparent nested prefabs. Technically you can, but things can get pretty ugly.
But you can move around root networkobjects.

**Comment by emredesu** [comment]
Hey! Sorry for the late response, I was not home for a while.

Basically in my project, I have a Skeleton character that can shoot projectiles. These projectiles are pooled as its child objects as such:

image

When spawning a projectile, I enable it using `NetworkBehaviour.Spawn()`, and call `NetworkObject.UnsetParent()` so that the projectile does not move with its parents' movement after it's been spawned. This works well. However, when I try to reparent this projectile when I'm done with it using `NetworkObject.SetParent()`, it fails with the error message in question. Upon further inspection of the documentation (because I was confused as to why I was getting this error message even after unpacking the prefabs of my projectiles), I have came to realize that it states that deparenting/re-parenting of nested NetworkObjects is not supported. This is why I believe that this error message is misleading, since the real problem is NetworkObjects being nested, not prefabs.

**Comment by FirstGearGames** [comment]
Ah I see what you are saying. I should probably add some sort of log when unparenting as well.

**Comment by emredesu** [comment]
Yes please! I am super down for this change if it will not cause things to break!

**Comment by FirstGearGames** [comment]
> Yes please! I am super down for this change if it will not cause things to break!

I updated the debug print and made it so you can reparent to the original.

**Pull request closed without merging**
